package mx.juanito.agro.service;
import mx.juanito.agro.config.AppProperties;import mx.juanito.agro.api.dto.LecturaRequest;import mx.juanito.agro.domain.entity.*;import mx.juanito.agro.domain.enums.*;import mx.juanito.agro.motor.MotorRiego;import mx.juanito.agro.repository.*;
import org.springframework.stereotype.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.http.HttpStatus;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;import org.springframework.web.client.RestClient;import org.springframework.http.client.SimpleClientHttpRequestFactory;
@Service
public class AgroService {
 final ParcelaRepository parcelas; final LecturaRepository lecturas; final RecomendacionRepository recomendaciones; final AppProperties props; final MotorRiego motor=new MotorRiego(); final Map<Long,Double> lluvia=new HashMap<>(); final Map<String,WeatherCache> weatherCache=new HashMap<>();
 record WeatherCache(Instant at,double mm){} record Weather(double mm,boolean available){}
 public AgroService(ParcelaRepository p,LecturaRepository l,RecomendacionRepository r,AppProperties a){parcelas=p;lecturas=l;recomendaciones=r;props=a;}
 Parcela parcela(Long id){return parcelas.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Parcela inexistente."));}
 Instant ahora(Long id){return props.relojSimulado?lecturas.findByParcelaIdOrderByFechaAsc(id).stream().map(Lectura::getFecha).max(Comparator.naturalOrder()).orElse(Instant.now()):Instant.now();}
 public record Nodo(String nodoId,Double humedad,Double bateriaV,Instant fecha,EstadoNodo estado){}
 public record Estado(Long parcelaId,String nombre,Cultivo cultivo,Nivel nivel,Accion accion,String motivo,Double humedadPromedio,Double humedadPeor,double umbralRiego,double capacidadCampo,double lluvia48hMm,boolean climaDisponible,Map<String,Object> calculo,List<Nodo> nodos,List<String> avisos,Map<String,Object> recomendacionActual){}
 public Estado estado(Long id){Parcela p=parcela(id);Instant ref=ahora(id);List<Lectura> all=lecturas.findByParcelaIdOrderByFechaAsc(id);Map<String,List<Lectura>> grupos=new LinkedHashMap<>();all.forEach(x->grupos.computeIfAbsent(x.getNodoId(),k->new ArrayList<>()).add(x));List<Nodo> ns=new ArrayList<>();List<Double> hs=new ArrayList<>();List<String> avisos=new ArrayList<>();for(var e:grupos.entrySet()){List<Lectura> xs=e.getValue();Lectura x=xs.get(xs.size()-1);EstadoNodo en=EstadoNodo.OK;if(Duration.between(x.getFecha(),ref).toMinutes()>props.lecturas.maxAntiguedadMin){en=EstadoNodo.SIN_SENAL;avisos.add("El sensor "+e.getKey()+" no envía datos desde hace "+Math.max(1,Duration.between(x.getFecha(),ref).toHours())+" h.");}else if(xs.size()>=props.lecturas.congeladoN&&xs.subList(xs.size()-props.lecturas.congeladoN,xs.size()).stream().map(Lectura::getHumedad).distinct().count()==1){en=EstadoNodo.CONGELADO;avisos.add("El sensor "+e.getKey()+" parece congelado (siempre marca lo mismo).");}else if(x.getBateriaV()!=null&&x.getBateriaV()<props.lecturas.bateriaBajaV){en=EstadoNodo.BATERIA_BAJA;avisos.add("Batería baja en el sensor "+e.getKey()+".");}ns.add(new Nodo(e.getKey(),x.getHumedad(),x.getBateriaV(),x.getFecha(),en));if(en==EstadoNodo.OK||en==EstadoNodo.BATERIA_BAJA)hs.add(x.getHumedad());}
 Weather w=clima(p,ref);double rain=w.mm();var r=motor.calcular(new MotorRiego.Parametros(p.getSuelo(),p.getAreaM2(),p.getCaudalLh(),rain,props.riego.laminaMaxPorRiegoMm,props.riego.lluviaSuficienteMm,props.riego.margenAviso,props.riego.margenExceso,props.riego.revisarDeNuevoHoras),hs);if(!grupos.isEmpty()&&hs.isEmpty())r=new MotorRiego.Resultado(Nivel.GRIS,Accion.REVISAR_NODO,"Los sensores no están enviando datos válidos.",0,0,0,0,null,null,r.umbralRiego(),r.capacidadCampo());List<Recomendacion> vig=recomendaciones.findByParcelaIdAndVigenteTrueAndDecisionIsNull(id);Map<String,Object> rec=null;if(!vig.isEmpty()){Recomendacion q=vig.get(0);rec=new HashMap<>();rec.put("id",q.getId());rec.put("accion",q.getAccion());rec.put("decision",q.getDecision());}Map<String,Object> calc=Map.of("laminaMm",r.laminaMm(),"litros",r.litros(),"minutosGoteo",r.minutosGoteo()==null?0:r.minutosGoteo(),"pendienteMm",r.pendienteMm());return new Estado(id,p.getNombre(),p.getCultivo(),r.nivel(),r.accion(),r.motivo(),r.humedadPromedio(),r.humedadPeor(),r.umbralRiego(),r.capacidadCampo(),rain,w.available(),calc,ns,avisos,rec);}
 private Weather clima(Parcela p,Instant ref){if(!"real".equalsIgnoreCase(props.clima.modo))return new Weather(lluvia.getOrDefault(p.getId(),0d),true);String key=p.getLatitud()+","+p.getLongitud();WeatherCache c=weatherCache.get(key);if(c!=null&&c.at().plus(30,java.time.temporal.ChronoUnit.MINUTES).isAfter(Instant.now()))return new Weather(c.mm(),true);try{SimpleClientHttpRequestFactory f=new SimpleClientHttpRequestFactory();f.setConnectTimeout(3000);f.setReadTimeout(3000);Map<?,?> body=RestClient.builder().requestFactory(f).build().get().uri("https://api.open-meteo.com/v1/forecast?latitude="+p.getLatitud()+"&longitude="+p.getLongitud()+"&hourly=precipitation&forecast_days=3&timezone=UTC").retrieve().body(Map.class);Map<?,?> hourly=(Map<?,?>)body.get("hourly");List<?> times=(List<?>)hourly.get("time"),precip=(List<?>)hourly.get("precipitation");double sum=0;int count=0;for(int i=0;i<Math.min(times.size(),precip.size())&&count<48;i++){Instant t=Instant.parse(times.get(i).toString());if(!t.isBefore(ref)){sum+=Double.parseDouble(precip.get(i).toString());count++;}}weatherCache.put(key,new WeatherCache(Instant.now(),sum));return new Weather(sum,true);}catch(Exception e){return new Weather(0,false);}}
 @Transactional public Map<String,Object> crearLectura(LecturaRequest d){Parcela p=parcela(d.parcelaId());if(!Double.isFinite(d.humedad())||d.humedad()<props.lecturas.humedadMinValida||d.humedad()>props.lecturas.humedadMaxValida)throw new IllegalArgumentException("La humedad debe estar entre "+props.lecturas.humedadMinValida+" y "+props.lecturas.humedadMaxValida);Lectura l=lecturas.save(new Lectura(d.parcelaId(),d.nodoId(),d.humedad(),d.tempSueloC(),d.bateriaV(),d.fecha()==null?Instant.now():d.fecha()));Estado e=estado(p.getId());if(e.accion()==Accion.NADA){recomendaciones.findByParcelaIdAndVigenteTrueAndDecisionIsNull(p.getId()).forEach(x->x.setVigente(false));}else{List<Recomendacion> pendientes=recomendaciones.findByParcelaIdAndVigenteTrueAndDecisionIsNull(p.getId());if(!pendientes.isEmpty()&&pendientes.get(0).getAccion()==e.accion()){Recomendacion x=pendientes.get(0);x.actualizar(p.getId(),e.nivel(),e.accion(),e.motivo(),(double)e.calculo().get("laminaMm"),(double)e.calculo().get("litros"),(Integer)e.calculo().get("minutosGoteo"),(double)e.calculo().get("pendienteMm"),ahora(p.getId()));}else{pendientes.forEach(x->x.setVigente(false));boolean silencio=recomendaciones.findByParcelaIdOrderByCreadaEnDesc(p.getId()).stream().anyMatch(x->x.getAccion()==e.accion()&&x.getDecision()!=null&&x.getDecididaEn()!=null&&x.getDecididaEn().isAfter(ahora(p.getId()).minus(props.recomendaciones.silencioHoras,java.time.temporal.ChronoUnit.HOURS)));if(!silencio){Recomendacion x=new Recomendacion();x.actualizar(p.getId(),e.nivel(),e.accion(),e.motivo(),(double)e.calculo().get("laminaMm"),(double)e.calculo().get("litros"),(Integer)e.calculo().get("minutosGoteo"),(double)e.calculo().get("pendienteMm"),ahora(p.getId()));recomendaciones.save(x);}}}var actual=recomendaciones.findByParcelaIdAndVigenteTrueAndDecisionIsNull(p.getId()).stream().findFirst().orElse(null);Map<String,Object> out=new HashMap<>();out.put("id",l.getId());out.put("nivel",e.nivel());out.put("accion",e.accion());out.put("recomendacionId",actual==null?null:actual.getId());return out;}
 public double lluvia(Long id){parcela(id);return lluvia.getOrDefault(id,0d);} public void lluvia(Long id,double mm){parcela(id);lluvia.put(id,mm);}public void reset(Long id){parcela(id);lecturas.deleteAll(lecturas.findByParcelaIdOrderByFechaAsc(id));recomendaciones.deleteAll(recomendaciones.findByParcelaIdOrderByCreadaEnDesc(id));lluvia.remove(id);}
 public List<Recomendacion> recs(Long id){parcela(id);return recomendaciones.findByParcelaIdOrderByCreadaEnDesc(id);} public Recomendacion actual(Long id){return recomendaciones.findByParcelaIdAndVigenteTrueAndDecisionIsNull(id).stream().findFirst().orElse(null);}
 public Recomendacion decision(Long id,Decision d){Recomendacion r=recomendaciones.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Recomendación inexistente."));if(r.getDecision()!=null)throw new ResponseStatusException(HttpStatus.CONFLICT,"Esta recomendación ya fue respondida.");r.decidir(d,ahora(r.getParcelaId()));return r;}
 public List<Lectura> lecturas(Long id,int horas,String nodo){parcela(id);Instant ref=ahora(id),desde=ref.minus(horas,java.time.temporal.ChronoUnit.HOURS);var ls=lecturas.findByParcelaIdAndFechaBetweenOrderByFechaAsc(id,desde,ref);return nodo==null?ls:ls.stream().filter(x->nodo.equals(x.getNodoId())).toList();}
 public Map<String,Object> tierra(Long id){
  Parcela p=parcela(id);Instant ref=ahora(id);ZoneId zone=ZoneId.of(props.zona);Map<LocalDate,List<Double>> dias=new HashMap<>();
  for(Lectura l:lecturas.findByParcelaIdAndFechaBetweenOrderByFechaAsc(id,ref.minus(7,java.time.temporal.ChronoUnit.DAYS),ref))dias.computeIfAbsent(l.getFecha().atZone(zone).toLocalDate(),k->new ArrayList<>()).add(l.getHumedad());
  double cc=cc(p.getSuelo()),um=umbral(p.getSuelo());int exceso=0,secos=0;for(List<Double> v:dias.values()){double m=v.stream().mapToDouble(x->x).average().orElse(0);if(m>cc+props.riego.margenExceso)exceso++;if(m<=um)secos++;}
  Instant desde=ref.minus(7,java.time.temporal.ChronoUnit.DAYS);List<Recomendacion> rs=recomendaciones.findByParcelaIdOrderByCreadaEnDesc(id).stream().filter(x->x.getDecididaEn()!=null&&!x.getDecididaEn().isBefore(desde)).toList();int reg= (int)rs.stream().filter(x->x.getDecision()==Decision.VOY_A_REGAR||x.getDecision()==Decision.YA_REGUE).count();int evit=(int)rs.stream().filter(x->x.getDecision()==Decision.VOY_A_ESPERAR&&(x.getAccion()==Accion.ESPERAR||x.getAccion()==Accion.NO_REGAR)).count();String estado,mensaje,consejo;
  if(dias.isEmpty()){estado="GRIS";mensaje="Aún no hay datos de tu tierra.";consejo="—";}else if(exceso+secos>=4){estado="ROJO";mensaje="Tu suelo ha pasado muchos días fuera de lo ideal.";consejo="Revisa tu calendario de riego con un técnico.";}else if(exceso>=1){estado="AMARILLO";mensaje="Hubo días con exceso de agua.";consejo="Evitar el exceso de agua ayuda a conservar los nutrientes del suelo.";}else if(secos>=1){estado="AMARILLO";mensaje="Hubo días con el suelo muy seco.";consejo="Un riego parejo evita que el fruto se raje.";}else{estado="VERDE";mensaje="Tu tierra ha estado bien cuidada esta semana.";consejo="Sigue así: mantener la humedad estable mejora la calidad del fruto.";}
  return Map.of("parcelaId",id,"estado",estado,"mensaje",mensaje,"consejo",consejo,"diasConDatos",dias.size(),"diasExceso",exceso,"diasSecos",secos,"riegosRegistrados",reg,"riegosEvitados",evit);
 }
 public Map<String,Object> impacto(Long id,int diasSolicitados){Parcela p=parcela(id);int dias=Math.max(1,diasSolicitados);Instant ref=ahora(id),desde=ref.minus(dias,java.time.temporal.ChronoUnit.DAYS);ZoneId zone=ZoneId.of(props.zona);Map<LocalDate,List<Double>> porDia=new HashMap<>();for(Lectura l:lecturas.findByParcelaIdAndFechaBetweenOrderByFechaAsc(id,desde,ref))porDia.computeIfAbsent(l.getFecha().atZone(zone).toLocalDate(),k->new ArrayList<>()).add(l.getHumedad());double cc=cc(p.getSuelo()),um=umbral(p.getSuelo());int enRango=(int)porDia.values().stream().filter(v->{double m=v.stream().mapToDouble(x->x).average().orElse(0);return m>=um&&m<=cc+props.riego.margenExceso;}).count();List<Recomendacion> rs=recomendaciones.findByParcelaIdOrderByCreadaEnDesc(id).stream().filter(x->x.getDecididaEn()!=null&&!x.getDecididaEn().isBefore(desde)).toList();int reg=(int)rs.stream().filter(x->x.getDecision()==Decision.VOY_A_REGAR||x.getDecision()==Decision.YA_REGUE).count();int evit=(int)rs.stream().filter(x->x.getDecision()==Decision.VOY_A_ESPERAR&&(x.getAccion()==Accion.ESPERAR||x.getAccion()==Accion.NO_REGAR)).count();double porcentaje=porDia.isEmpty()?0:100d*enRango/porDia.size(),litros=evit*(props.impacto.riegoTradicionalMm/.9)*p.getAreaM2();return Map.of("parcelaId",id,"periodoDias",dias,"diasConDatos",porDia.size(),"diasEnRangoIdeal",enRango,"porcentajeDiasEnRango",porcentaje,"riegosRegistrados",reg,"riegosEvitados",evit,"litrosAhorradosEstimados",litros,"supuesto","Estimación: cada riego evitado ahorra "+props.impacto.riegoTradicionalMm+" mm del riego tradicional de referencia. Validar este valor con datos del productor.");}
 private double cc(Suelo s){return switch(s){case ARENOSO->.12;case FRANCO->.27;case ARCILLOSO->.38;};} private double umbral(Suelo s){return cc(s)-.4*(cc(s)-switch(s){case ARENOSO->.05;case FRANCO->.12;case ARCILLOSO->.22;});}
}




